

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VisualOS.DAL
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Model1Container : DbContext
{
    public Model1Container()
        : base("name=Model1Container")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<tb_cargo> tb_cargo { get; set; }

    public DbSet<tb_ordemservico> tb_ordemservico { get; set; }

    public DbSet<tb_servico> tb_servico { get; set; }

    public DbSet<tb_usuario> tb_usuario { get; set; }

    public DbSet<rl_agenda> rl_agenda { get; set; }

    public DbSet<rl_cargo_usuario> rl_cargo_usuario { get; set; }

    public DbSet<rl_servico_os> rl_servico_os { get; set; }

}

}

