
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VisualOS.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class rl_agenda
{

    public int ID_Usuario { get; set; }

    public int ID_Ordem_Servico { get; set; }

    public System.DateTime Agendamento { get; set; }



    public virtual tb_ordemservico tb_ordemservico { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }

}

}
