
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VisualOS.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class rl_cargo_usuario
{

    public int ID_Cargo { get; set; }

    public int ID_Usuario { get; set; }

    public System.DateTime Data { get; set; }



    public virtual tb_cargo tb_cargo { get; set; }

    public virtual tb_usuario tb_usuario { get; set; }

}

}
