//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VisualOS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_p4l_log
    {
        public int ID { get; set; }
        public string ID_Usuario { get; set; }
        public string Browser { get; set; }
        public string Complemento { get; set; }
        public System.DateTime DataHora { get; set; }
        public string IP { get; set; }
        public string Operacao { get; set; }
    }
}
