
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace VisualOS.DAL
{

using System;
    using System.Collections.Generic;
    
public partial class tb_servico
{

    public tb_servico()
    {

        this.rl_servico_os = new HashSet<rl_servico_os>();

    }


    public int ID { get; set; }

    public string Nome { get; set; }

    public string Descricao { get; set; }



    public virtual ICollection<rl_servico_os> rl_servico_os { get; set; }

}

}
